tasks:
  - name: install dotnet environment
    init: |
      wget https://dot.net/v1/dotnet-install.sh && chmod +x dotnet-install.sh && ./dotnet-install.sh 
      echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.bashrc
      echo 'export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools' >> ~/.bashrc
    command: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
      dotnet sdk check

  - name: install Apache Kafka Cluster
    command: |
      gp open README.md
      gp open lab1-firstStepsWithKafka/readme.md
      export PUBLIC_IP=127.0.0.1
      docker-compose up
      gp env KAFKAJS_NO_PARTITIONER_WARNING=1

ports:

  # AKHQ
  - port: 28042
    onOpen: open-preview
    visibility: public

  # Node
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public
  - port: 3002
    onOpen: ignore
    visibility: public
  - port: 3005 # CRM service
    onOpen: ignore
    visibility: public
  - port: 3006 # IoT Platform Service
    onOpen: ignore
    visibility: public


  # Kafka Brokers, Zookeeper 
  - port: 2188
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 9093
    onOpen: ignore
  - port: 9094
    onOpen: ignore
  - port: 2181
    onOpen: ignore
  - port: 9992
    onOpen: ignore
  - port: 9993
    onOpen: ignore
  - port: 9994
    onOpen: ignore

  # Kafka Schema Registry 
  - port: 8081
    onOpen: ignore

  # Kafka REST Proxy 
  - port: 8082
    onOpen: ignore
    visibility: public


vscode:
  extensions:
    - ms-azuretools.vscode-docker    